version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgresdb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgresdb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: