-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Country" ADD VALUE 'AFGHANISTAN';
ALTER TYPE "Country" ADD VALUE 'ALBANIA';
ALTER TYPE "Country" ADD VALUE 'ALGERIA';
ALTER TYPE "Country" ADD VALUE 'ANDORRA';
ALTER TYPE "Country" ADD VALUE 'ANGOLA';
ALTER TYPE "Country" ADD VALUE 'ANTIGUA_AND_BARBUDA';
ALTER TYPE "Country" ADD VALUE 'ARGENTINA';
ALTER TYPE "Country" ADD VALUE 'ARMENIA';
ALTER TYPE "Country" ADD VALUE 'AUSTRALIA';
ALTER TYPE "Country" ADD VALUE 'AUSTRIA';
ALTER TYPE "Country" ADD VALUE 'AZERBAIJAN';
ALTER TYPE "Country" ADD VALUE 'BAHAMAS';
ALTER TYPE "Country" ADD VALUE 'BAHRAIN';
ALTER TYPE "Country" ADD VALUE 'BANGLADESH';
ALTER TYPE "Country" ADD VALUE 'BARBADOS';
ALTER TYPE "Country" ADD VALUE 'BELARUS';
ALTER TYPE "Country" ADD VALUE 'BELGIUM';
ALTER TYPE "Country" ADD VALUE 'BELIZE';
ALTER TYPE "Country" ADD VALUE 'BENIN';
ALTER TYPE "Country" ADD VALUE 'BHUTAN';
ALTER TYPE "Country" ADD VALUE 'BOLIVIA';
ALTER TYPE "Country" ADD VALUE 'BOSNIA_AND_HERZEGOVINA';
ALTER TYPE "Country" ADD VALUE 'BOTSWANA';
ALTER TYPE "Country" ADD VALUE 'BRAZIL';
ALTER TYPE "Country" ADD VALUE 'BRUNEI';
ALTER TYPE "Country" ADD VALUE 'BULGARIA';
ALTER TYPE "Country" ADD VALUE 'BURKINA_FASO';
ALTER TYPE "Country" ADD VALUE 'BURUNDI';
ALTER TYPE "Country" ADD VALUE 'CABO_VERDE';
ALTER TYPE "Country" ADD VALUE 'CAMBODIA';
ALTER TYPE "Country" ADD VALUE 'CAMEROON';
ALTER TYPE "Country" ADD VALUE 'CANADA';
ALTER TYPE "Country" ADD VALUE 'CENTRAL_AFRICAN_REPUBLIC';
ALTER TYPE "Country" ADD VALUE 'CHAD';
ALTER TYPE "Country" ADD VALUE 'CHILE';
ALTER TYPE "Country" ADD VALUE 'CHINA';
ALTER TYPE "Country" ADD VALUE 'COLOMBIA';
ALTER TYPE "Country" ADD VALUE 'COMOROS';
ALTER TYPE "Country" ADD VALUE 'CONGO';
ALTER TYPE "Country" ADD VALUE 'COSTA_RICA';
ALTER TYPE "Country" ADD VALUE 'CROATIA';
ALTER TYPE "Country" ADD VALUE 'CUBA';
ALTER TYPE "Country" ADD VALUE 'CYPRUS';
ALTER TYPE "Country" ADD VALUE 'CZECH_REPUBLIC';
ALTER TYPE "Country" ADD VALUE 'DENMARK';
ALTER TYPE "Country" ADD VALUE 'DJIBOUTI';
ALTER TYPE "Country" ADD VALUE 'DOMINICA';
ALTER TYPE "Country" ADD VALUE 'DOMINICAN_REPUBLIC';
ALTER TYPE "Country" ADD VALUE 'ECUADOR';
ALTER TYPE "Country" ADD VALUE 'EGYPT';
ALTER TYPE "Country" ADD VALUE 'EL_SALVADOR';
ALTER TYPE "Country" ADD VALUE 'EQUATORIAL_GUINEA';
ALTER TYPE "Country" ADD VALUE 'ERITREA';
ALTER TYPE "Country" ADD VALUE 'ESTONIA';
ALTER TYPE "Country" ADD VALUE 'ESWATINI';
ALTER TYPE "Country" ADD VALUE 'ETHIOPIA';
ALTER TYPE "Country" ADD VALUE 'FIJI';
ALTER TYPE "Country" ADD VALUE 'FINLAND';
ALTER TYPE "Country" ADD VALUE 'FRANCE';
ALTER TYPE "Country" ADD VALUE 'GABON';
ALTER TYPE "Country" ADD VALUE 'GAMBIA';
ALTER TYPE "Country" ADD VALUE 'GEORGIA';
ALTER TYPE "Country" ADD VALUE 'GERMANY';
ALTER TYPE "Country" ADD VALUE 'GHANA';
ALTER TYPE "Country" ADD VALUE 'GREECE';
ALTER TYPE "Country" ADD VALUE 'GRENADA';
ALTER TYPE "Country" ADD VALUE 'GUATEMALA';
ALTER TYPE "Country" ADD VALUE 'GUINEA';
ALTER TYPE "Country" ADD VALUE 'GUINEA_BISSAU';
ALTER TYPE "Country" ADD VALUE 'GUYANA';
ALTER TYPE "Country" ADD VALUE 'HAITI';
ALTER TYPE "Country" ADD VALUE 'HONDURAS';
ALTER TYPE "Country" ADD VALUE 'HUNGARY';
ALTER TYPE "Country" ADD VALUE 'ICELAND';
ALTER TYPE "Country" ADD VALUE 'INDIA';
ALTER TYPE "Country" ADD VALUE 'INDONESIA';
ALTER TYPE "Country" ADD VALUE 'IRAN';
ALTER TYPE "Country" ADD VALUE 'IRAQ';
ALTER TYPE "Country" ADD VALUE 'IRELAND';
ALTER TYPE "Country" ADD VALUE 'ISRAEL';
ALTER TYPE "Country" ADD VALUE 'ITALY';
ALTER TYPE "Country" ADD VALUE 'JAMAICA';
ALTER TYPE "Country" ADD VALUE 'JAPAN';
ALTER TYPE "Country" ADD VALUE 'JORDAN';
ALTER TYPE "Country" ADD VALUE 'KAZAKHSTAN';
ALTER TYPE "Country" ADD VALUE 'KENYA';
ALTER TYPE "Country" ADD VALUE 'KIRIBATI';
ALTER TYPE "Country" ADD VALUE 'KOSOVO';
ALTER TYPE "Country" ADD VALUE 'KUWAIT';
ALTER TYPE "Country" ADD VALUE 'KYRGYZSTAN';
ALTER TYPE "Country" ADD VALUE 'LAOS';
ALTER TYPE "Country" ADD VALUE 'LATVIA';
ALTER TYPE "Country" ADD VALUE 'LEBANON';
ALTER TYPE "Country" ADD VALUE 'LESOTHO';
ALTER TYPE "Country" ADD VALUE 'LIBERIA';
ALTER TYPE "Country" ADD VALUE 'LIBYA';
ALTER TYPE "Country" ADD VALUE 'LIECHTENSTEIN';
ALTER TYPE "Country" ADD VALUE 'LITHUANIA';
ALTER TYPE "Country" ADD VALUE 'LUXEMBOURG';
ALTER TYPE "Country" ADD VALUE 'MADAGASCAR';
ALTER TYPE "Country" ADD VALUE 'MALAWI';
ALTER TYPE "Country" ADD VALUE 'MALAYSIA';
ALTER TYPE "Country" ADD VALUE 'MALDIVES';
ALTER TYPE "Country" ADD VALUE 'MALI';
ALTER TYPE "Country" ADD VALUE 'MALTA';
ALTER TYPE "Country" ADD VALUE 'MARSHALL_ISLANDS';
ALTER TYPE "Country" ADD VALUE 'MAURITANIA';
ALTER TYPE "Country" ADD VALUE 'MAURITIUS';
ALTER TYPE "Country" ADD VALUE 'MEXICO';
ALTER TYPE "Country" ADD VALUE 'MICRONESIA';
ALTER TYPE "Country" ADD VALUE 'MOLDOVA';
ALTER TYPE "Country" ADD VALUE 'MONACO';
ALTER TYPE "Country" ADD VALUE 'MONGOLIA';
ALTER TYPE "Country" ADD VALUE 'MONTENEGRO';
ALTER TYPE "Country" ADD VALUE 'MOROCCO';
ALTER TYPE "Country" ADD VALUE 'MOZAMBIQUE';
ALTER TYPE "Country" ADD VALUE 'MYANMAR';
ALTER TYPE "Country" ADD VALUE 'NAMIBIA';
ALTER TYPE "Country" ADD VALUE 'NAURU';
ALTER TYPE "Country" ADD VALUE 'NEPAL';
ALTER TYPE "Country" ADD VALUE 'NETHERLANDS';
ALTER TYPE "Country" ADD VALUE 'NEW_ZEALAND';
ALTER TYPE "Country" ADD VALUE 'NICARAGUA';
ALTER TYPE "Country" ADD VALUE 'NIGER';
ALTER TYPE "Country" ADD VALUE 'NORTH_KOREA';
ALTER TYPE "Country" ADD VALUE 'NORTH_MACEDONIA';
ALTER TYPE "Country" ADD VALUE 'NORWAY';
ALTER TYPE "Country" ADD VALUE 'OMAN';
ALTER TYPE "Country" ADD VALUE 'PAKISTAN';
ALTER TYPE "Country" ADD VALUE 'PALAU';
ALTER TYPE "Country" ADD VALUE 'PALESTINE';
ALTER TYPE "Country" ADD VALUE 'PANAMA';
ALTER TYPE "Country" ADD VALUE 'PAPUA_NEW_GUINEA';
ALTER TYPE "Country" ADD VALUE 'PARAGUAY';
ALTER TYPE "Country" ADD VALUE 'PERU';
ALTER TYPE "Country" ADD VALUE 'PHILIPPINES';
ALTER TYPE "Country" ADD VALUE 'POLAND';
ALTER TYPE "Country" ADD VALUE 'PORTUGAL';
ALTER TYPE "Country" ADD VALUE 'QATAR';
ALTER TYPE "Country" ADD VALUE 'ROMANIA';
ALTER TYPE "Country" ADD VALUE 'RUSSIA';
ALTER TYPE "Country" ADD VALUE 'RWANDA';
ALTER TYPE "Country" ADD VALUE 'SAINT_KITTS_AND_NEVIS';
ALTER TYPE "Country" ADD VALUE 'SAINT_LUCIA';
ALTER TYPE "Country" ADD VALUE 'SAINT_VINCENT_AND_THE_GRENADINES';
ALTER TYPE "Country" ADD VALUE 'SAMOA';
ALTER TYPE "Country" ADD VALUE 'SAN_MARINO';
ALTER TYPE "Country" ADD VALUE 'SAO_TOME_AND_PRINCIPE';
ALTER TYPE "Country" ADD VALUE 'SAUDI_ARABIA';
ALTER TYPE "Country" ADD VALUE 'SENEGAL';
ALTER TYPE "Country" ADD VALUE 'SERBIA';
ALTER TYPE "Country" ADD VALUE 'SEYCHELLES';
ALTER TYPE "Country" ADD VALUE 'SIERRA_LEONE';
ALTER TYPE "Country" ADD VALUE 'SINGAPORE';
ALTER TYPE "Country" ADD VALUE 'SLOVAKIA';
ALTER TYPE "Country" ADD VALUE 'SLOVENIA';
ALTER TYPE "Country" ADD VALUE 'SOLOMON_ISLANDS';
ALTER TYPE "Country" ADD VALUE 'SOMALIA';
ALTER TYPE "Country" ADD VALUE 'SOUTH_AFRICA';
ALTER TYPE "Country" ADD VALUE 'SOUTH_KOREA';
ALTER TYPE "Country" ADD VALUE 'SOUTH_SUDAN';
ALTER TYPE "Country" ADD VALUE 'SPAIN';
ALTER TYPE "Country" ADD VALUE 'SRI_LANKA';
ALTER TYPE "Country" ADD VALUE 'SUDAN';
ALTER TYPE "Country" ADD VALUE 'SURINAME';
ALTER TYPE "Country" ADD VALUE 'SWEDEN';
ALTER TYPE "Country" ADD VALUE 'SWITZERLAND';
ALTER TYPE "Country" ADD VALUE 'SYRIA';
ALTER TYPE "Country" ADD VALUE 'TAIWAN';
ALTER TYPE "Country" ADD VALUE 'TAJIKISTAN';
ALTER TYPE "Country" ADD VALUE 'TANZANIA';
ALTER TYPE "Country" ADD VALUE 'THAILAND';
ALTER TYPE "Country" ADD VALUE 'TIMOR_LESTE';
ALTER TYPE "Country" ADD VALUE 'TOGO';
ALTER TYPE "Country" ADD VALUE 'TONGA';
ALTER TYPE "Country" ADD VALUE 'TRINIDAD_AND_TOBAGO';
ALTER TYPE "Country" ADD VALUE 'TUNISIA';
ALTER TYPE "Country" ADD VALUE 'TURKEY';
ALTER TYPE "Country" ADD VALUE 'TURKMENISTAN';
ALTER TYPE "Country" ADD VALUE 'TUVALU';
ALTER TYPE "Country" ADD VALUE 'UGANDA';
ALTER TYPE "Country" ADD VALUE 'UKRAINE';
ALTER TYPE "Country" ADD VALUE 'UNITED_ARAB_EMIRATES';
ALTER TYPE "Country" ADD VALUE 'UNITED_KINGDOM';
ALTER TYPE "Country" ADD VALUE 'UNITED_STATES';
ALTER TYPE "Country" ADD VALUE 'URUGUAY';
ALTER TYPE "Country" ADD VALUE 'UZBEKISTAN';
ALTER TYPE "Country" ADD VALUE 'VANUATU';
ALTER TYPE "Country" ADD VALUE 'VATICAN_CITY';
ALTER TYPE "Country" ADD VALUE 'VENEZUELA';
ALTER TYPE "Country" ADD VALUE 'VIETNAM';
ALTER TYPE "Country" ADD VALUE 'YEMEN';
ALTER TYPE "Country" ADD VALUE 'ZAMBIA';
ALTER TYPE "Country" ADD VALUE 'ZIMBABWE';

-- CreateTable
CREATE TABLE "Share" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "sold" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Share_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Transaction" (
    "id" TEXT NOT NULL,
    "buyerId" TEXT NOT NULL,
    "sellerId" TEXT NOT NULL,
    "shareId" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Share" ADD CONSTRAINT "Share_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_shareId_fkey" FOREIGN KEY ("shareId") REFERENCES "Share"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
